### ISSUE TITLE
Not all wireless cards are supported-- realtek

### ISSUE THREAD

**Issue by impetus1** [mszoek/helium#39]
I use a realtek card on a toshiba satellite and native freebsd loads the urtw driver. This however recognizes the card, but the driver requires rtwn(4) in order to establish connection. Including the driver in the installer would fix this issue and I believe this is what furybsd achieved in their installer iso.
Another freebsd-specific issue is the matter of connecting different wireless configurations, like open or wpa-psk but this is something to bring up to freebsd.

**Comment by mszoek** [comment]
Thanks for trying it! The installer has not been a big priority TBH - I have been more focused on getting the toolchain and Cocoa frameworks working, and starting on the X system stuff now. It is definitely not a daily driver yet, and I have only run this in Vmware Fusion. I'll look into using the FuryBSD installer or at least including those modules for you though! Or feel free to submit a PR :) I'm also starting to talk with the creator of helloSystem about possible collabs now that I'm aware of it.

**Comment by mszoek** [comment]
Hi @impetus1 -- I have been looking at the ISO image and my installed system, and both seem to have rtwn.ko available. Does it maybe just need to be included in loader.conf?
