### ISSUE TITLE
Apple ARM compatibility

### ISSUE THREAD

**Issue by tyu1996** [mszoek/helium#44]
Just curious, of course I don't expect now to be happen: Will this project happens to be Apple ARM compatible in the future? And how difficult will be to make the current ARM64 FreeBSD compatible with Apple ARM?

Since Apple shifted to its own chip and can foresee many apps will eventually move to Apple ARM support as their priority.

**Comment by mszoek** [comment]
Apple's move to ARM silicon was one of the drivers behind starting this project. The goal is to be "compatible enough" at a source code level that Mac apps can be built on Helium just as they are on macOS. The result is a FreeBSD ELF executable packaged in a .app bundle. So, someone could likely do that on FreeBSD ARM just as well as on FreeBSD x64 - with a little porting effort. The value proposition to software vendors is then "it's minimal extra effort to support Helium and get these extra users", which I hope will encourage both open-source and commercial apps to build for it.

Apps themselves are not directly compatible: you can't take a macOS bundle and run it on Helium, or take a Helium bundle and run it on macOS. (Although you could make a "fat" bundle with both executables that does run on both!) I would like to integrate some of Darling's work at some point to add that compatibility but that's way down the road. And AFAIK that project does not support ARM (yet?) either.
